# Generated by Django 3.0.5 on 2020-04-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_data',
            name='cvc',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='card_data',
            name='month',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='card_data',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
